import type { Alert, ResidentRequest, Settings, WorkOrder, Zone } from "./types";

export const zones: Zone[] = [
  {
    id: "z-502",
    name: "Zone 502",
    floor: "5th Floor",
    type: "Residential",
    temperature: 78.6,
    setpoint: 72,
    occupancy: 62,
    humidity: 48,
    trend: [73, 73.4, 74, 74.8, 76, 77.2, 78.6],
  },
  {
    id: "ahu-3",
    name: "AHU-3 Supply",
    floor: "Roof",
    type: "Mechanical",
    temperature: 68.8,
    setpoint: 62,
    occupancy: 0,
    humidity: 38,
    trend: [62, 62.4, 64, 65, 66.2, 67.4, 68.8],
  },
  {
    id: "conf-2",
    name: "Conference Room",
    floor: "2nd Floor",
    type: "Amenity",
    temperature: 70.8,
    setpoint: 72,
    occupancy: 25,
    humidity: 46,
    trend: [71.8, 71.5, 71, 70.9, 70.6, 70.8, 70.8],
  },
  {
    id: "z-401",
    name: "Zone 401",
    floor: "4th Floor",
    type: "Residential",
    temperature: 72.1,
    setpoint: 72,
    occupancy: 68,
    humidity: 43,
    trend: [71.8, 72, 72.2, 72.1, 71.9, 72, 72.1],
  },
  {
    id: "z-301",
    name: "Zone 301",
    floor: "3rd Floor",
    type: "Residential",
    temperature: 71.5,
    setpoint: 72,
    occupancy: 71,
    humidity: 44,
    trend: [72.4, 72, 71.7, 71.6, 71.4, 71.5, 71.5],
  },
  {
    id: "lobby",
    name: "Main Lobby",
    floor: "1st Floor",
    type: "Lobby",
    temperature: 73,
    setpoint: 72,
    occupancy: 35,
    humidity: 41,
    trend: [71.9, 72.2, 72.5, 72.6, 72.8, 72.9, 73],
  },
  {
    id: "plant",
    name: "Chiller Plant",
    floor: "Basement",
    type: "Mechanical",
    temperature: 68.4,
    setpoint: 68,
    occupancy: 0,
    humidity: 36,
    trend: [68.1, 68.2, 68.2, 68.3, 68.5, 68.4, 68.4],
  },
];

export const initialAlerts: Alert[] = [
  {
    id: "a-1",
    zoneId: "z-502",
    title: "5th Floor · Zone 502",
    reason: "Temperature is 6.6°F above setpoint and has risen for 45 minutes.",
    severity: "critical",
    detectedAt: "10:12 AM",
    status: "open",
  },
  {
    id: "a-2",
    zoneId: "ahu-3",
    title: "AHU-3 · Supply air",
    reason: "Supply air is 6.8°F above the expected operating range.",
    severity: "attention",
    detectedAt: "9:48 AM",
    status: "open",
  },
  {
    id: "a-3",
    zoneId: "conf-2",
    title: "2nd Floor · Conference Room",
    reason: "CO₂ reading is above the comfort threshold while occupied.",
    severity: "attention",
    detectedAt: "9:31 AM",
    status: "open",
  },
  {
    id: "a-4",
    zoneId: "plant",
    title: "Chiller Plant · Efficiency",
    reason: "Cooling efficiency is 21% below its seven-day baseline.",
    severity: "info",
    detectedAt: "9:05 AM",
    status: "open",
  },
];

export const initialWorkOrders: WorkOrder[] = [
  {
    id: "1258",
    title: "High temperature investigation",
    location: "5th Floor · Zone 502",
    priority: "high",
    status: "open",
    assignee: "Unassigned",
    createdAt: "10:12 AM",
    sourceAlertId: "a-1",
  },
  {
    id: "1257",
    title: "Supply sensor troubleshooting",
    location: "Roof · AHU-3",
    priority: "medium",
    status: "scheduled",
    assignee: "Maya Chen",
    createdAt: "9:48 AM",
    sourceAlertId: "a-2",
  },
  {
    id: "1256",
    title: "CO₂ sensor recalibration",
    location: "2nd Floor · Conference Room",
    priority: "medium",
    status: "open",
    assignee: "Luis Reyes",
    createdAt: "9:31 AM",
    sourceAlertId: "a-3",
  },
  {
    id: "1255",
    title: "Performance check",
    location: "Basement · Chiller Plant",
    priority: "low",
    status: "scheduled",
    assignee: "Maya Chen",
    createdAt: "9:05 AM",
    sourceAlertId: "a-4",
  },
];

export const residentRequests: ResidentRequest[] = [
  {
    id: "r-1",
    resident: "Nadia Torres",
    unit: "5B",
    message: "The bedroom has been warmer than the thermostat setting since last night.",
    createdAt: "8:42 AM",
    status: "new",
  },
  {
    id: "r-2",
    resident: "Evan Lee",
    unit: "3F",
    message: "Airflow is weak in the living room, but the temperature is still comfortable.",
    createdAt: "Yesterday",
    status: "in-review",
  },
  {
    id: "r-3",
    resident: "Priya Shah",
    unit: "4C",
    message: "The hallway vent makes a rattling sound after the system starts.",
    createdAt: "Monday",
    status: "closed",
  },
];

export const defaultSettings: Settings = {
  buildingName: "Riverside Commons",
  comfortLow: 68,
  comfortHigh: 76,
  notifications: true,
  reducedMotion: false,
};
