import type { ServiceRequest, Technician } from "./types";

export const technicians: Technician[] = [
  {
    id: "t1",
    name: "Marcus Hill",
    trades: ["HVAC", "Life safety"],
    rating: 4.9,
    jobsThisWeek: 3,
    available: ["Mon 9–1", "Tue 1–5", "Thu 8–12"],
  },
  {
    id: "t2",
    name: "Briana Lopez",
    trades: ["Plumbing", "General repair"],
    rating: 4.8,
    jobsThisWeek: 2,
    available: ["Mon 1–5", "Wed 9–1", "Fri 2–6"],
  },
  {
    id: "t3",
    name: "Devon Carter",
    trades: ["Electrical", "Life safety", "Appliance"],
    rating: 4.7,
    jobsThisWeek: 4,
    available: ["Tue 8–12", "Wed 1–5", "Fri 9–1"],
  },
  {
    id: "t4",
    name: "Tyler Nguyen",
    trades: ["Appliance", "General repair", "Inspection"],
    rating: 4.9,
    jobsThisWeek: 3,
    available: ["Mon 10–2", "Tue 10–2", "Thu 1–5"],
  },
  {
    id: "t5",
    name: "Jordan Patel",
    trades: ["Locksmith", "Inspection", "Pest control", "Landscaping"],
    rating: 4.6,
    jobsThisWeek: 2,
    available: ["Wed 2–6", "Thu 10–2", "Fri 10–2"],
  },
];

export const initialRequests: ServiceRequest[] = [
  {
    id: "12548",
    resident: "Nadia Torres",
    unit: "204",
    property: "Northfield Lofts",
    summary: "AC not cooling",
    details: "The bedroom is warm even though the thermostat is set to 72.",
    trade: "HVAC",
    confidence: 94,
    responsibility: "building",
    availability: ["Mon 9–1", "Tue 1–5"],
    preferredTechnician: "Marcus Hill",
    assignedTechnician: "Marcus Hill",
    scheduledSlot: "Mon 9–1",
    status: "scheduled",
    estimatedPay: 145,
  },
  {
    id: "12547",
    resident: "Evan Lee",
    unit: "8B",
    property: "Pine Ridge Townhomes",
    summary: "Leaking kitchen faucet",
    details: "A steady drip started below the handle.",
    trade: "Plumbing",
    confidence: 96,
    responsibility: "building",
    availability: ["Mon 1–5", "Fri 2–6"],
    assignedTechnician: "Briana Lopez",
    status: "accepted",
    estimatedPay: 95,
  },
  {
    id: "12543",
    resident: "Priya Shah",
    unit: "101",
    property: "Lakeside Villas",
    summary: "Outlet not working",
    details: "The outlet beside the desk has no power.",
    trade: "Electrical",
    confidence: 92,
    responsibility: "review",
    availability: ["Tue 8–12"],
    assignedTechnician: "Devon Carter",
    status: "offered",
    estimatedPay: 120,
  },
  {
    id: "12539",
    resident: "Omar Reed",
    unit: "3A",
    property: "Main St. Flats",
    summary: "Dishwasher not draining",
    details: "Water remains after the cycle.",
    trade: "Appliance",
    confidence: 93,
    responsibility: "building",
    availability: ["Tue 10–2"],
    assignedTechnician: "Tyler Nguyen",
    status: "in-progress",
    estimatedPay: 110,
  },
  {
    id: "12536",
    resident: "Mina Park",
    unit: "205",
    property: "Oakview Heights",
    summary: "Patio door won’t lock",
    details: "The latch no longer catches.",
    trade: "Locksmith",
    confidence: 90,
    responsibility: "building",
    availability: ["Wed 2–6"],
    status: "triage",
    estimatedPay: 85,
  },
];
